services:
  highscore-service:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./highscore.json:/app/highscore.json

  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:9090
